from typing import Dict, List, Tuple

from app.agents.base import BaseAgent


class RecommendationAgent(BaseAgent):
    def run(self, context: Dict) -> Dict:
        normalized = context["normalized"]
        interests = normalized["interests"]
        budget = normalized["budget"]
        group_type = normalized["group_type"]

        scored: List[Tuple[float, Dict]] = []
        for item in context.get("candidates", []):
            score = 0.0
            if group_type in item["best_for"]:
                score += 1.5
            interest_overlap = len(set(interests) & set(item["tags"]))
            score += interest_overlap * 0.5
            if item["estimated_cost"] <= budget:
                score += 1.0
            else:
                score -= 0.5
            scored.append((score, item))

        scored.sort(key=lambda x: x[0], reverse=True)
        ranked = [item for _, item in scored]
        top = ranked[:3]
        recommendations = []
        for item in top:
            recommendations.append(
                {
                    "destination": item["name"],
                    "region": item["region"],
                    "estimated_cost": item["estimated_cost"],
                    "best_for": item["best_for"],
                    "tags": item["tags"],
                    "notes": [
                        f"Fits {normalized['days']} days",
                        f"Group type match: {normalized['group_type']}",
                    ],
                }
            )
        self._add_llm_note(
            context,
            f"Top recommendations: {[item['destination'] for item in recommendations]}",
        )
        return {
            "ranked": ranked,
            "recommendations": recommendations,
            "summary": "Generated by multi-agent workflow",
        }

